### ISSUE TITLE
Error when running gulp command

### ISSUE THREAD

**Issue by clpacheco90** [google/closure-compiler-js#13]
Hi,
  When I try to run the gulp, I'm getting this error. I'm using the same code in [sample page](https://github.com/google/closure-compiler-js/tree/master/samples)

```
C:\auroraorange\node_modules\google-closure-compiler-js\lib\gulp.js:116
  return function(compilationOptions={}, pluginOptions={}) {
                                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\auroraorange\node_modules\google-closure-compiler-js\index.js:25:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\auroraorange\gulpfile.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at execute (C:\Users\Calvin\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:24:18)
    at Liftoff.handleArguments (C:\Users\Calvin\AppData\Roaming\npm\node_modules\gulp-cli\index.js:149:63)
    at Liftoff.<anonymous> (C:\Users\Calvin\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\liftoff\index.js:198:16)
    at module.exports (C:\Users\Calvin\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> (C:\Users\Calvin\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\liftoff\index.js:190:9)
    at C:\Users\Calvin\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\liftoff\index.js:164:9
    at C:\Users\Calvin\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\v8flags\index.js:108:14
    at C:\Users\Calvin\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\v8flags\index.js:36:12
    at C:\Users\Calvin\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\v8flags\index.js:47:7
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by samthor** [comment]
I've updated the `lib/gulp.js` script for Node 4.5 LTS (which doesn't support default = params).

This will go out in the next release.
