### ISSUE TITLE
compiler.gulp() crashes: Cannot find module vinyl

### ISSUE THREAD

**Issue by RoxKilly** [google/closure-compiler-js#30]
I've installed with:
```
npm install --save-dev closure-compiler-js
```
Installation was successful:
```
google-closure-compiler-js@20160916.0.0 node_modules\google-closure-compiler-js
├── webpack-core@0.6.8 (source-map@0.4.4, source-list-map@0.1.6)
└── gulp-util@3.0.7 (array-differ@1.0.0, beeper@1.1.0, array-uniq@1.0.3, object-assign@3.0.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, fancy-log@1.2.0, vinyl@0.5.3, gulp
log@1.0.0, chalk@1.1.3, lodash.template@3.6.2, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)
```

To create a gulp task I try to follow the README:
```
closureCompiler = require('google-closure-compiler-js').gulp();
```
But as soon as I add `.gulp()` to the end of that line, `Gulp` crashes (I can no longer list or execute tasks) with this error:
> module.js:327
    throw err;
    ^
>
> Error: Cannot find module 'vinyl'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.module.exports.Transform [as gulp] (\node_modules\google-closure-compiler-js\lib\gulp.js:52:16)
    at Object.<anonymous> (\gulpfile.js:365:63)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (\node_modules\gulp\node_modules\liftoff\index.js:198:16)
    at module.exports (\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> (\node_modules\gulp\node_modules\liftoff\index.js:190:9)
    at \node_modules\gulp\node_modules\liftoff\index.js:164:9
    at \node_modules\gulp\node_modules\v8flags\index.js:108:14
    at \node_modules\gulp\node_modules\v8flags\index.js:36:12
    at \node_modules\gulp\node_modules\v8flags\index.js:47:7
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3

`vinyl` was installed as you can see in the console excerpt above the error. The folder below has content:
```
/node_modules/google-closure-compiler-js/node_modules/gulp-util/node_modules/vinyl
```

I have (package.json):
```
"google-closure-compiler-js": "^20160916.0.0",
"gulp": "^3.9.1",
```

Any idea why I'm seeing this error? Should I also install `google-closure-compiler`?

**Comment by RoxKilly** [comment]
I did `npm install --save-dev vinyl` to make that go away (it installed `vinyl 2.0`)
