### ISSUE TITLE
Error when using --use_strict

### ISSUE THREAD

**Issue by srod** [google/closure-compiler-js#35]
When using `node --use_strict`, it throw an error :
```
TypeError: Cannot set property '$gwtExport' of undefined
    at /Users/rodolphe/Dropbox/www/github/node-minify/node_modules/google-closure-compiler-js/jscomp.js:7410:491339
    at Object.<anonymous> (/Users/rodolphe/Dropbox/www/github/node-minify/node_modules/google-closure-compiler-js/jscomp.js:7410:491399)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/rodolphe/Dropbox/www/github/node-minify/node_modules/google-closure-compiler-js/compile.js:24:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/rodolphe/Dropbox/www/github/node-minify/node_modules/google-closure-compiler-js/index.js:25:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/rodolphe/Dropbox/www/github/node-minify/examples/gcc.js:1:116)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
`node -v v6.9.1`
`npm -v 4.0.2`

You can reproduce it with the example code sample and run it with `node --use_strict`
```
const compile = require('google-closure-compiler-js').compile;

const flags = {
  jsCode: [{src: 'const x = 1 + 2;'}],
};
const out = compile(flags);
console.info(out.compiledCode);  // will print 'var x = 3;\n'
```
It seems to fail when require jscomp.js

Related to: https://github.com/srod/node-minify/issues/122

**Comment by ChadKillingsworth** [comment]
If this is still an issue, please refile it at https://github.com/google/closure-compiler-npm

**Comment by srod** [comment]
Does it means that we have to switch from the NPM package `google-closure-compiler-js` to `google-closure-compiler` ?

**Comment by ChadKillingsworth** [comment]
It does. The JS version is now published there as well.
