### ISSUE TITLE
jscomp_off, jscomp_warning and jscomp_error options not available in JS version

### ISSUE THREAD

**Issue by nazar-pc** [google/closure-compiler-js#73]
Latest JS version simply do know understand these options:
```
Exception: closure compiler error: { Error: java.lang.RuntimeException: Unhandled flag: jscomp_off
    at KI.nG [as Tf] (/media/Data/emscripten/node_modules/google-closure-compiler-js/jscomp.js:7823:22584)
    at KI.qG [as Vf] (/media/Data/emscripten/node_modules/google-closure-compiler-js/jscomp.js:7823:22779)
    at KI.lG (/media/Data/emscripten/node_modules/google-closure-compiler-js/jscomp.js:2257:48)
    at KI.tG (/media/Data/emscripten/node_modules/google-closure-compiler-js/jscomp.js:616:19)
    at KI (/media/Data/emscripten/node_modules/google-closure-compiler-js/jscomp.js:618:19)
    at Ccd (/media/Data/emscripten/node_modules/google-closure-compiler-js/jscomp.js:7440:77)
    at aJ (/media/Data/emscripten/node_modules/google-closure-compiler-js/jscomp.js:1782:29)
    at dJ (/media/Data/emscripten/node_modules/google-closure-compiler-js/jscomp.js:3102:44)
    at /media/Data/emscripten/node_modules/google-closure-compiler-js/jscomp.js:3289:46
    at module.exports (/media/Data/emscripten/node_modules/google-closure-compiler-js/compile.js:31:15)
    at ready (/media/Data/emscripten/node_modules/google-closure-compiler-js/cmd.js:107:18)
    at Promise.all.then.arr (/media/Data/emscripten/node_modules/google-closure-compiler-js/cmd.js:58:45)
    at <anonymous>
  '__java$exception': 
   { f: null,
     e: 'Unhandled flag: jscomp_off',
     backingJsObject: [Circular] } }
```

**Comment by MatrixFrog** [comment]
Was this working in a previous version? Which one? I'm not sure if we actually ported these flags to the JS version or not.

**Comment by nazar-pc** [comment]
No, it didn't work in previous versions either

**Comment by nazar-pc** [comment]
@MatrixFrog is it difficult to expose these options in JS version?

**Comment by qudg74** [comment]
@samthor, will you have time to look into this? I'd love to see these flags, too and say goodbye to Java.

**Comment by ChadKillingsworth** [comment]
This is now supported. Deployment has moved to https://github.com/google/closure-compiler-npm

**Comment by philipwalton** [comment]
@ChadKillingsworth I see you marked this as supported and tagged it with `fixed-in-next-release`. Do you know when that release is shipping?

I looks like several versions of the main closure compiler project have been released since.

**Comment by ChadKillingsworth** [comment]
The release has shipped - but it has moved to the main npm repo. The JS version is now distributed there. This repo no longer is active.

**Comment by philipwalton** [comment]
Ahh, I see. It'd be nice if this repo's README were updated to explain that it's no longer being updated (currently that's not at all clear).

You might also consider adding a deprecation warning when users npm install it.

/cc @samthor
