### ISSUE TITLE
Error with Webpack 2

### ISSUE THREAD

**Issue by blacksonic** [google/closure-compiler-js#8]
I'm using Webpack 2.1.0-beta.21 and with a fresh install i get this error from ClosureCompiler:

```
Error: Cannot find module 'webpack-core/lib/RawSource'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at new module.exports (/home/blacksonic/workspace/babel-webpack-tree-shaking/node_modules/google-closure-compiler-js/lib/webpack.js:27:21)
    at Object.<anonymous> (/home/blacksonic/workspace/babel-webpack-tree-shaking/webpack.prod.config.js:36:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at module.exports (/home/blacksonic/workspace/babel-webpack-tree-shaking/node_modules/webpack/bin/convert-argv.js:93:13)
    at Object.<anonymous> (/home/blacksonic/workspace/babel-webpack-tree-shaking/node_modules/webpack/bin/webpack.js:130:40)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

**Comment by blacksonic** [comment]
Here is a similar issue with other library https://github.com/webpack/compression-webpack-plugin/issues/19

**Comment by blacksonic** [comment]
i see it is a duplicate

**Comment by blacksonic** [comment]
Here is a similar issue https://github.com/webpack/compression-webpack-plugin/issues/19

**Comment by jameswyse** [comment]
I have a similar problem with react-formal not being able to resolve lodash moduless. Problem started when I moved to the new `es2015` preset with `{ modules: false }` setting..

I ended up setting aliases for the broken modules in my config 😢 

```js
alias: {
  'lodash/object/pick': path.resolve('node_modules', 'lodash', 'pick.js'),
  'lodash/array/uniq': path.resolve('node_modules', 'lodash', 'uniq.js'),
  'lodash/object/omit': path.resolve('node_modules', 'lodash', 'omit.js')
}
```

**Comment by samthor** [comment]
We've updated the dependencies to require `webpack-core` now. However, I'd love suggestions that don't require that. We just use it for the `RawSource` etc output classes.

**Comment by blacksonic** [comment]
It might have smaller impact if extracted to a different package.
