### ISSUE TITLE
INTERNAL COMPILER ERROR: async functions should have already been converted

### ISSUE THREAD

**Issue by Zubnix** [google/closure-compiler-js#97]
```
function hh(a){cf(a);if(OL(a,42)){throw Cjb(GL(a,42))}if(OL(a,153)){throw Cjb(GL(a,153))}}
                                  ^
Error: java.lang.RuntimeException: INTERNAL COMPILER ERROR. Please report this problem.  async functions should have already been converted   Node(FUNCTION ): browser.bundle.js:6213:15   static async create (sessionId) {   Parent(ASSIGN): browser.bundle.js:6213:15   static async create (sessionId) { 
    at TJ.tH [as ag] (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:8093:23242)
    at TJ.wH [as cg] (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:8093:23437)
    at TJ.sH (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:2315:48)
    at TJ.AH (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:615:19)
    at new TJ (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:617:19)
    at vIb (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:5861:95)
    at TBc (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:4683:106)
    at UBc (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:5533:126)
    at t4c (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:7040:301)
    at B2b.C2b [as Ag] (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:8093:219415)
    at zNc (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:7657:306)
    at ANc.BNc [as Ag] (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:8093:319859)
    at pNc (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:5907:146)
    at YGb (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:5211:91)
    at _Hb (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:3503:69)
    at WIb.XIb [as qi] (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:8093:159481)
    at jJb (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:4841:36)
    at $Gb (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:7438:153)
    at jjd (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:7687:358)
    at hK (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:1828:29)
    at kK (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:3196:44)
    at /home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:3399:46
    at module.exports (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/compile.js:31:15)
    at files.forEach.name (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/lib/webpack.js:61:28)
    at Array.forEach (<anonymous>)
    at chunks.forEach.chunk (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/lib/webpack.js:49:17)
    at Array.forEach (<anonymous>)
    at Compilation.compilation.plugin (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/lib/webpack.js:47:16)
    at Compilation.applyPluginsAsyncSeries (/home/zubzub/git/greenfield/node_modules/tapable/lib/Tapable.js:206:13)
    at applyPluginsAsync.err (/home/zubzub/git/greenfield/node_modules/webpack/lib/Compilation.js:663:10)
```

Failing file:
https://github.com/udevbe/greenfield/blob/master/browser/src/BrowserSession.js

webpack config:
```
const path = require('path')
const ClosureCompiler = require('google-closure-compiler-js').webpack

module.exports = {
  entry: './browser/src/index.js',
  output: {
    path: path.resolve(__dirname, 'browser/public'),
    filename: 'browser.bundle.js'
  },
  plugins: [
    new ClosureCompiler({
      options: {
        languageIn: 'ECMASCRIPT6',
        languageOut: 'ECMASCRIPT5',
        // compilationLevel: 'ADVANCED',
        warningLevel: 'VERBOSE'
      }
    })
  ]
}
```

plain webpack'ed file attached:
[bundle.zip](https://github.com/google/closure-compiler-js/files/1863276/bundle.zip)

//edit
When trying to Java version, it complained about async being ecma8. So I changed the in & out language to 8 which resulted in an EPIPE error (using Java).
When using the javascript version I got the following error: #98

**Comment by ChadKillingsworth** [comment]
languageOut: 'ECMASCRIPT8' -> That's not yet a supported output language. Highest output language currently supported is ECMASCRIPT6.
