### ISSUE TITLE
INTERNAL COMPILER ERROR. undefined   Node(FUNCTION )

### ISSUE THREAD

**Issue by Zubnix** [google/closure-compiler-js#98]
```
(node:5107) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:4014
function hh(a){cf(a);if(OL(a,42)){throw Cjb(GL(a,42))}if(OL(a,153)){throw Cjb(GL(a,153))}}
                                  ^

Error: java.lang.RuntimeException: INTERNAL COMPILER ERROR. Please report this problem.  undefined   Node(FUNCTION ): browser.bundle.js:4281:2   constructor (client, id, version) {   Parent(ASSIGN): browser.bundle.js:4280:0 wfs.ClientResource = class extends wfs.Resource { 
    at TJ.tH [as ag] (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:8093:23242)
    at TJ.wH [as cg] (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:8093:23437)
    at TJ.sH (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:2315:48)
    at TJ.AH (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:615:19)
    at new TJ (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:617:19)
    at vIb (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:5861:95)
    at TBc (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:4683:106)
    at _Bc (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:6106:168)
    at M8c (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:5790:131)
    at O8c (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:3095:58)
    at VWb.WWb [as Ag] (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:8093:200135)
    at zNc (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:7657:306)
    at ANc.BNc [as Ag] (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:8093:319859)
    at pNc (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:5907:146)
    at YGb (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:5211:91)
    at _Hb (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:3503:69)
    at WIb.XIb [as qi] (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:8093:159481)
    at jJb (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:4841:36)
    at $Gb (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:7438:153)
    at jjd (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:7687:358)
    at hK (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:1828:29)
    at kK (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:3196:44)
    at /home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/jscomp.js:3399:46
    at module.exports (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/compile.js:31:15)
    at files.forEach.name (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/lib/webpack.js:61:28)
    at Array.forEach (<anonymous>)
    at chunks.forEach.chunk (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/lib/webpack.js:49:17)
    at Array.forEach (<anonymous>)
    at compilation.plugin (/home/zubzub/git/greenfield/node_modules/google-closure-compiler-js/lib/webpack.js:47:16)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/zubzub/git/greenfield/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/zubzub/git/greenfield/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.additionalAssets.callAsync.err (/home/zubzub/git/greenfield/node_modules/webpack/lib/Compilation.js:950:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/zubzub/git/greenfield/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/zubzub/git/greenfield/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (/home/zubzub/git/greenfield/node_modules/webpack/lib/Compilation.js:946:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/zubzub/git/greenfield/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/zubzub/git/greenfield/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/home/zubzub/git/greenfield/node_modules/webpack/lib/Compilation.js:888:27)
    at hooks.make.callAsync.err (/home/zubzub/git/greenfield/node_modules/webpack/lib/Compiler.js:479:17)
    at _err0 (eval at create (/home/zubzub/git/greenfield/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (/home/zubzub/git/greenfield/node_modules/webpack/lib/Compilation.js:756:12)
    at processModuleDependencies.err (/home/zubzub/git/greenfield/node_modules/webpack/lib/Compilation.js:695:9)
    at process._tickCallback (internal/process/next_tick.js:112:11)
```

Bug details are the same as reported in #97 but with a different webpack config:

```
const path = require('path')
const ClosureCompiler = require('google-closure-compiler-js').webpack

module.exports = {
  entry: './browser/src/index.js',
  output: {
    path: path.resolve(__dirname, 'browser/public'),
    filename: 'browser.bundle.js'
  },
  plugins: [
    new ClosureCompiler({
      options: {
        languageIn: 'ECMASCRIPT8',
        languageOut: 'ECMASCRIPT8',
        compilationLevel: 'ADVANCED',
        warningLevel: 'VERBOSE'
      }
    })
  ]
}
```

Java plugin, same settings:

```
const path = require('path')
const ClosureCompilerPlugin = require('webpack-closure-compiler')

module.exports = {
  entry: './browser/src/index.js',
  output: {
    path: path.resolve(__dirname, 'browser/public'),
    filename: 'browser.bundle.js'
  },
  plugins: [
    new ClosureCompilerPlugin({
      compiler: {
        language_in: 'ECMASCRIPT8',
        language_out: 'ECMASCRIPT8',
        compilation_level: 'ADVANCED'
      }
    })
  ]
}
```

```
(node:6421) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:841:14)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:427:12)
    at onwrite (_stream_writable.js:449:5)
    at _destroy (internal/streams/destroy.js:39:7)
    at Socket._destroy (net.js:545:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:843:10)

```

**Comment by ChadKillingsworth** [comment]
languageOut: 'ECMASCRIPT8' -> That's not yet a supported output language. Highest output language currently supported is ECMASCRIPT6
